User holdings using SuiClient Api
AlphaFiTech/alphafi-sdk pull request #25
Opened 2024-09-03 17:06 UTC by OctoSauce

2024-09-04 09:10 UTC, jangid requested changes

2024-09-04 09:10 UTC, jangid commented on src/getUserHoldingsUsd.ts
> +  const map = new Map<string, number>();
give some name to map. what it is used for, purpose etc.

2024-09-04 09:10 UTC, jangid commented on src/getUserHoldings.ts
> +// function mergeDuplicateHoldings(
remove commented lines

2024-09-04 09:10 UTC, jangid commented on src/getUserHoldings.ts
> +  pools?: string[];
change to poolName and create a type for complex params.

2024-09-04 09:10 UTC, jangid commented on src/getUserHoldings.ts
> +type alphaReceiptFields = {
move this to "./src/types.ts" and Type names should be CapilatlizedCamelCase.

2024-09-04 09:10 UTC, jangid commented on src/getUserHoldings.ts
> +type otherRecceiptFields = {
same as previous comment.

2024-09-04 09:33 UTC, jangid requested changes

2024-09-04 09:33 UTC, jangid commented on src/common/maps.ts
> +export async function getPoolConversionMap(): Promise<Map<PoolName, string>> {
rename to getPoolExchangeRateMap

2024-09-04 09:33 UTC, jangid commented on src/common/maps.ts
> +export async function getCetusInvestorTicksMap(): Promise<{
return type object should have key of type PoolName and not string.

2024-09-06 07:02 UTC, jangid requested changes

2024-09-06 07:02 UTC, jangid commented on src/sui-sdk/transactions/fetchTransactions.ts
> +      if (Number(laterTime) < params.startTime) {
why we need this check? Are the start and end date params not working in queryTransactionBlocks?

2024-09-06 07:02 UTC, jangid commented on src/sui-sdk/transactions/types.ts
> +export type FetchTransactionParams = {
Add 'order' attribute to the FetchTransactionParams. So that we can reuse it for specific order.

2024-09-06 08:00 UTC, jangid requested changes

2024-09-06 08:00 UTC, jangid commented on src/getDataFromEvents.ts
Rename this file to getActivity.ts

2024-09-06 08:18 UTC, jangid requested changes

2024-09-06 08:18 UTC, jangid commented on src/getHolders.ts
How is `getHolders` function different from `getHoldersFromEvents` in the file `getDataFromEvents`? Aren't both of them returning same accounts in the same time-span?

2024-09-06 12:40 UTC, OctoSauce commented on src/sui-sdk/transactions/fetchTransactions.ts
> +      if (Number(laterTime) < params.startTime) {
queryTransactionBlocks is a suiClient API, it doesn't have timestamp checks. This is for having timestamp check.

2024-09-06 12:44 UTC, OctoSauce commented
Resolve overlap with timestamp checks in src/sui-sdk/transactions/fetchTransactions.ts The transactions should be exactly in the timestamp range, not just based on pages

2024-09-06 13:48 UTC, OctoSauce commented on src/getHolders.ts
Yes both use different ways

2024-09-06 14:44 UTC, OctoSauce commented
> Resolve overlap with timestamp checks in src/sui-sdk/transactions/fetchTransactions.ts The transactions should be exactly in the timestamp range, not just based on pages

Resolved

2024-09-09 09:59 UTC, closed without merging